In [64]:
import pandas as pd

In [85]:
from sklearn.datasets import load_iris
data = load_iris()

type(data)
isinstance(data, dict)
data.keys()

sklearn.utils._bunch.Bunch

True

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [88]:
data.feature_names
data.target_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [91]:
type(data.data)
type(data.target)

numpy.ndarray

numpy.ndarray

In [92]:
data.data.shape
data.target.shape

(150, 4)

(150,)

In [69]:
data.data[:4]
data.target[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

array([0, 0, 0, 0])

In [70]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df.head()
df.shape

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

(150, 4)

## Can load directly as data frame

In [93]:
data = load_iris(as_frame=True)
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [95]:
type(data.data)
type(data.target)

pandas.DataFrame

pandas.Series

In [97]:
data.data.head()
data.data.shape

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

(150, 4)

In [98]:
data.target.head()
data.target.shape

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

(150,)

## Directly obtain the feature matrix and target vector

In [100]:
X, y = load_iris(return_X_y=True)
type(X)
type(y)

numpy.ndarray

numpy.ndarray

In [101]:
X.shape
y.shape

(150, 4)

(150,)