In [134]:
import numpy as np
import pandas as pd

In [135]:
df = pd.read_csv("data/Week1_GA_dataset.csv")
df.sample(5)
df.shape

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
359,2009-06-07,2009,Bridgeport,95130.0,184000.0,Two Family,Duplex,4,4,1307.0,1.025953,South
9311,2022-02-10,2022,Stamford,967530.0,1050000.0,?,Detached House,3,2,1043.0,1.003979,North
5079,2016-10-28,2016,Greenwich,396200.0,750000.0,Single Family,Detached House,3,2,944.0,1.348259,North
5973,2017-10-13,2017,West Hartford,193970.0,296125.0,?,Detached House,3,1,923.0,1.388283,North
1062,2010-07-24,2010,Norwalk,290220.0,467000.0,Single Family,Detached House,3,1,1007.0,1.025846,West

(10000, 12)

In [136]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  str
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   str
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  str
 6   Residential        10000 non-null  str
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 937.6 KB

In [137]:
# (df == '?')  # bool mask
# (df == '?').sum()  # col-wise totals
(df == '?').sum().sum()  # net total across all cols

np.int64(1823)

In [138]:
df[df == '?'] = pd.NA
(df == '?').sum().sum()  # no more "?"

np.int64(0)

In [139]:
df.iloc[692, 0]
df.iloc[546, 7]

'2009-11-16'

np.int64(3)

In [140]:
df['Locality'].value_counts().shape

(7,)

In [141]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  str
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   str
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           8177 non-null   str
 6   Residential        10000 non-null  str
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 937.6 KB

In [142]:
mask = df.isnull().sum(axis=1) > 2
indices_to_drop = df[mask].index
df.drop(indices_to_drop, axis=0)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [143]:
df.dropna()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
...,...,...,...,...,...,...,...,...,...,...,...,...
9986,2022-09-28,2022,Norwalk,305820.0,535000.0,Single Family,Detached House,3,2,1080.0,1.003979,West
9987,2022-09-28,2022,Norwalk,450510.0,677000.0,Single Family,Detached House,3,1,1000.0,1.003979,North
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East